---
- name: Include install tasks
  ansible.builtin.include_tasks: install.yml
  when: zsh_action == "install"

- name: Include remove tasks
  ansible.builtin.include_tasks: remove.yml
  when: zsh_action == "remove"
